(() => {
  "use strict";
  const CONFIG = window.KAIOKEN_MARKET_CONFIG || {};
  const configured = /^https:\/\/[a-z0-9-]+\.supabase\.co$/i.test(CONFIG.supabaseUrl || "") && /^sb_publishable_/i.test(CONFIG.supabasePublishableKey || "");
  const $ = id => document.getElementById(id);
  const access=$("access-panel"), accessTitle=$("access-title"), accessText=$("access-text"), app=$("admin-app"), status=$("status");
  const itemDialog=$("item-dialog"), itemForm=$("item-form"), importDialog=$("import-dialog"), importForm=$("import-form"), listingDialog=$("listing-dialog"), listingForm=$("listing-form");
  let db=null,user=null,role=null,items=[],listings=[],reports=[],staff=[];
  const categories=new Set(["equipment","scroll","consumable","etc","material","currency","dragon_ball","gachapon","special","service","other"]);
  const kinds=new Set(["maple","kaioken_custom","service"]);
  const clean=(v,max=600)=>String(v??"").trim().slice(0,max);
  const boolish=v=>["true","1","yes","y","on"].includes(String(v??"").trim().toLowerCase());
  const slugify=s=>clean(s,160).toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,160);
  const roleLabel=r=>r==="editor"?"Editor":r==="game_developer"?"Game Developer":"No staff role";
  const canStaff=()=>role==="editor"||role==="game_developer";
  const setStatus=(msg="",type="")=>{status.textContent=msg;status.className="status"+(type?` ${type}`:"");};
  function scopedStatus(id,msg="",type=""){const n=$(id);n.textContent=msg;n.className="status"+(type?` ${type}`:"");}
  function setAccess(mode,title,text){access.className="access-panel"+(mode?` ${mode}`:"");accessTitle.textContent=title;accessText.textContent=text;}
  function userName(){if(!user)return"Not signed in";const m=user.user_metadata||{};return clean(m.full_name||m.name||m.user_name||m.preferred_username||user.email||"Discord user",80);}
  function userAvatar(){if(!user)return"";const m=user.user_metadata||{};return clean(m.avatar_url||m.picture||"",1000);}
  function accountUI(){
    $("account-name").textContent=userName();
    $("discord-login").hidden=!!user;$("sign-out").hidden=!user;
    $("role-badge").hidden=!role;$("role-badge").textContent=roleLabel(role);
    const avatar=$("account-avatar"),url=userAvatar();
    avatar.hidden=!user;avatar.replaceChildren();
    if(user){if(url){const img=document.createElement("img");img.src=url;img.alt="";img.referrerPolicy="no-referrer";img.onerror=()=>{avatar.textContent=userName().slice(0,1).toUpperCase();};avatar.append(img);}else avatar.textContent=userName().slice(0,1).toUpperCase();}
  }
  function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;}
  function fmtMesos(n){const v=Number(n||0);return v.toLocaleString()+" mesos";}
  function fmtDate(v){try{return new Date(v).toLocaleString();}catch{return String(v||"");}}

  async function refreshAuth(){
    if(!db)return;const {data}=await db.auth.getUser();user=data?.user||null;role=null;accountUI();app.hidden=true;
    if(!user){setAccess("","Discord sign-in required","Sign in with a Discord account that has a staff role.");return;}
    setAccess("","Checking staff role…","Your Discord login is valid. Verifying permissions in Supabase.");
    const {data:r,error}=await db.rpc("market_staff_role");
    if(error){console.error(error);setAccess("bad","Staff migration is not ready","Run market-staff-roles-migration.sql first.");return;}
    role=r||null;accountUI();
    if(!canStaff()){setAccess("bad","Access denied","This account does not have an Editor or Game Developer role.");return;}
    setAccess("ok",`${roleLabel(role)} access granted`,role==="editor"?"Full catalog, moderation, reports, staff roles and private guide access.":"Catalog, moderation, reports and private guide access. Team role management is Editor only.");
    $("team-tab-button").hidden=role!=="editor";app.hidden=false;await loadItems();
  }

  function switchTab(name){document.querySelectorAll(".staff-tabs .tab").forEach(b=>b.classList.toggle("active",b.dataset.tab===name));document.querySelectorAll(".tab-panel").forEach(p=>p.classList.toggle("active",p.id===`tab-${name}`));if(name==="listings")loadListings();if(name==="reports")loadReports();if(name==="team"&&role==="editor")loadStaff();}
  document.querySelectorAll(".staff-tabs .tab").forEach(b=>b.addEventListener("click",()=>switchTab(b.dataset.tab)));

  async function loadItems(){setStatus("Loading catalog…");const {data,error}=await db.from("market_items").select("*").order("sort_order").order("name");if(error){console.error(error);setStatus("Could not load catalog.","error");return;}items=Array.isArray(data)?data:[];setStatus(`Loaded ${items.length} catalog items.`,"success");renderItems();}
  function filteredItems(){const q=$("search").value.trim().toLowerCase(),cat=$("category-filter").value,enabled=$("enabled-filter").value;return items.filter(x=>{if(cat!=="all"&&x.category!==cat)return false;if(enabled==="enabled"&&!x.market_enabled)return false;if(enabled==="disabled"&&x.market_enabled)return false;if(!q)return true;const hay=[x.name,x.slug,x.category,x.subcategory,x.source_name,x.description,...(Array.isArray(x.aliases)?x.aliases:[])].map(v=>clean(v).toLowerCase()).join(" ");return hay.includes(q);});}
  function renderItems(){
    $("stat-total").textContent=items.length;$("stat-enabled").textContent=items.filter(x=>x.market_enabled).length;$("stat-custom").textContent=items.filter(x=>x.kind==="kaioken_custom").length;$("stat-unverified").textContent=items.filter(x=>!x.verified).length;
    const grid=$("item-grid");grid.replaceChildren();
    for(const row of filteredItems()){
      const card=el("article","item-card"+(row.market_enabled?"":" disabled"));const icon=el("div","item-icon");
      if(row.image_url){const img=document.createElement("img");img.src=row.image_url;img.alt="";img.loading="lazy";img.onerror=()=>{img.remove();icon.append(el("span","placeholder","📦"));};icon.append(img);}else icon.append(el("span","placeholder",row.category==="dragon_ball"?"🐉":"📦"));
      const main=el("div","item-main");main.append(el("h3","",row.name));const badges=el("div","badges");badges.append(el("span","badge",row.category.replaceAll("_"," ")));if(row.kind==="kaioken_custom")badges.append(el("span","badge custom","KaiokenMS"));badges.append(el("span","badge "+(row.verified?"verified":"unverified"),row.verified?"Verified":"Needs verify"));if(!row.market_enabled)badges.append(el("span","badge","Disabled"));main.append(badges);
      const meta=[];if(row.subcategory)meta.push(row.subcategory);if(row.maple_item_id)meta.push(`ID ${row.maple_item_id}`);if(row.source_name)meta.push(row.source_name);main.append(el("div","item-meta",meta.join(" • ")||row.slug));if(row.description)main.append(el("p","item-desc",row.description));
      const actions=el("div","item-actions");const edit=el("button","","Edit");edit.onclick=()=>openEditItem(row);const toggle=el("button","",row.market_enabled?"Disable":"Enable");toggle.onclick=()=>toggleEnabled(row);const del=el("button","danger","Delete");del.onclick=()=>deleteItem(row);actions.append(edit,toggle,del);card.append(icon,main,actions);grid.append(card);
    }
  }
  function resetItemForm(){itemForm.reset();$("item-id").value="";$("item-kind").value="maple";$("item-category").value="equipment";$("item-sort").value="0";$("item-tradable").checked=true;$("item-enabled").checked=true;$("item-metadata").value="{}";$("item-dialog-title").textContent="Add Item";$("form-status").textContent="";$("item-image-file").value="";}
  function openAddItem(){resetItemForm();itemDialog.showModal();}
  function openEditItem(row){resetItemForm();$("item-dialog-title").textContent=`Edit: ${row.name}`;$("item-id").value=row.id;$("item-name").value=row.name||"";$("item-slug").value=row.slug||"";$("item-kind").value=row.kind||"maple";$("item-category").value=row.category||"other";$("item-subcategory").value=row.subcategory||"";$("item-maple-id").value=row.maple_item_id||"";$("item-sort").value=row.sort_order||0;$("item-aliases").value=(row.aliases||[]).join(", ");$("item-description").value=row.description||"";$("item-source-name").value=row.source_name||"";$("item-source-url").value=row.source_url||"";$("item-image-url").value=row.image_url||"";$("item-tradable").checked=!!row.tradable;$("item-verified").checked=!!row.verified;$("item-enabled").checked=!!row.market_enabled;$("item-metadata").value=JSON.stringify(row.metadata||{},null,2);itemDialog.showModal();}
  async function uploadIcon(file){if(!file)return null;if(file.size>1024*1024)throw new Error("Icon must be 1 MB or smaller.");if(!/^image\/(png|jpeg|webp|gif)$/i.test(file.type))throw new Error("Use PNG, JPG, WEBP or GIF.");const ext=(file.name.split(".").pop()||"png").toLowerCase().replace(/[^a-z0-9]/g,"")||"png",path=`items/${crypto.randomUUID()}.${ext}`;const {error}=await db.storage.from("market-items").upload(path,file,{cacheControl:"3600",upsert:false,contentType:file.type});if(error)throw error;return db.storage.from("market-items").getPublicUrl(path).data.publicUrl;}
  async function saveItem(ev){ev.preventDefault();if(!canStaff())return;const fs=$("form-status");fs.className="status";fs.textContent="Saving…";try{let metadata={};try{metadata=JSON.parse($("item-metadata").value.trim()||"{}");}catch{throw new Error("Metadata JSON is invalid.");}const name=clean($("item-name").value,120),slug=slugify($("item-slug").value||name),kind=$("item-kind").value,category=$("item-category").value;if(!name||!slug)throw new Error("Name and slug are required.");if(!kinds.has(kind)||!categories.has(category))throw new Error("Invalid category or kind.");let imageUrl=clean($("item-image-url").value,1000)||null;const file=$("item-image-file").files?.[0];if(file)imageUrl=await uploadIcon(file);const mapleRaw=$("item-maple-id").value.trim();const payload={slug,name,kind,category,subcategory:clean($("item-subcategory").value,80)||null,maple_item_id:mapleRaw?Number(mapleRaw):null,image_url:imageUrl,source_name:clean($("item-source-name").value,100)||null,source_url:clean($("item-source-url").value,1000)||null,aliases:$("item-aliases").value.split(",").map(x=>clean(x,100)).filter(Boolean).slice(0,30),description:clean($("item-description").value,600)||null,metadata,tradable:$("item-tradable").checked,verified:$("item-verified").checked,market_enabled:$("item-enabled").checked,sort_order:Number($("item-sort").value||0)};const id=$("item-id").value;const q=id?db.from("market_items").update(payload).eq("id",id):db.from("market_items").insert(payload);const {error}=await q;if(error)throw error;itemDialog.close();await loadItems();}catch(e){console.error(e);fs.className="status error";fs.textContent=e.message||"Could not save item.";}}
  async function toggleEnabled(row){const {error}=await db.from("market_items").update({market_enabled:!row.market_enabled}).eq("id",row.id);if(error){setStatus(error.message,"error");return;}await loadItems();}
  async function deleteItem(row){if(!confirm(`Delete ${row.name}?\n\nDisable is safer if old listings may reference it.`))return;const {error}=await db.from("market_items").delete().eq("id",row.id);if(error){setStatus(`Delete blocked: ${error.message}. Try Disable instead.`,"error");return;}await loadItems();}
  function parseCSV(text){const rows=[];let row=[],field="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(quoted){if(c==='"'&&n==='"'){field+='"';i++;}else if(c==='"')quoted=false;else field+=c;}else{if(c==='"')quoted=true;else if(c===','){row.push(field);field="";}else if(c==='\n'){row.push(field.replace(/\r$/,"") );rows.push(row);row=[];field="";}else field+=c;}}if(field.length||row.length){row.push(field.replace(/\r$/,"") );rows.push(row);}if(!rows.length)return[];const headers=rows.shift().map(h=>h.trim());return rows.filter(r=>r.some(v=>v.trim())).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??""])));}
  function rowToPayload(r){const name=clean(r.name,120),slug=slugify(r.slug||name);if(!name||!slug)throw new Error("Every CSV row needs name/slug.");const kind=kinds.has(r.kind)?r.kind:"maple",category=categories.has(r.category)?r.category:"other";let metadata={};if(clean(r.metadata)){try{metadata=JSON.parse(r.metadata);}catch{throw new Error(`Invalid metadata JSON for ${name}`);}}return{slug,name,kind,category,subcategory:clean(r.subcategory,80)||null,maple_item_id:clean(r.maple_item_id)?Number(r.maple_item_id):null,image_url:clean(r.image_url,1000)||null,source_name:clean(r.source_name,100)||null,source_url:clean(r.source_url,1000)||null,aliases:clean(r.aliases,1000).split("|").map(x=>clean(x,100)).filter(Boolean),description:clean(r.description,600)||null,tradable:boolish(r.tradable),verified:boolish(r.verified),market_enabled:boolish(r.market_enabled),sort_order:Number(r.sort_order||0),metadata};}
  async function importCSV(ev){ev.preventDefault();const file=$("csv-file").files?.[0];if(!file)return;$("import-status").textContent="Reading CSV…";try{const raw=parseCSV(await file.text()).map(rowToPayload);if(!raw.length)throw new Error("CSV has no data rows.");for(let i=0;i<raw.length;i+=100){const {error}=await db.from("market_items").upsert(raw.slice(i,i+100),{onConflict:"slug"});if(error)throw error;}importDialog.close();setStatus(`Imported ${raw.length} rows.`,"success");await loadItems();}catch(e){console.error(e);$("import-status").className="status error";$("import-status").textContent=e.message||"Import failed.";}}
  function csvEscape(v){const s=String(v??"");return /[",\n\r]/.test(s)?`"${s.replaceAll('"','""')}"`:s;}
  function exportCSV(){const headers=["slug","name","kind","category","subcategory","maple_item_id","image_url","source_name","source_url","aliases","description","tradable","verified","market_enabled","sort_order","metadata"],lines=[headers.join(",")];for(const x of items){const row={...x,aliases:(x.aliases||[]).join("|"),metadata:JSON.stringify(x.metadata||{})};lines.push(headers.map(h=>csvEscape(row[h])).join(","));}const blob=new Blob(["\ufeff"+lines.join("\r\n")],{type:"text/csv;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`kaioken-market-catalog-${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000);}

  async function loadListings(){scopedStatus("listing-status","Loading all market posts…");const {data,error}=await db.from("market_listings").select("*").order("created_at",{ascending:false}).limit(500);if(error){console.error(error);scopedStatus("listing-status",error.message,"error");return;}listings=Array.isArray(data)?data:[];scopedStatus("listing-status",`Loaded ${listings.length} posts.`,"success");renderListings();}
  function filteredListings(){const q=$("listing-search").value.trim().toLowerCase(),state=$("listing-state-filter").value,side=$("listing-side-filter").value;return listings.filter(x=>{if(side!=="all"&&x.side!==side)return false;if(state==="open"&&(x.is_hidden||x.sold_at))return false;if(state==="hidden"&&!x.is_hidden)return false;if(state==="sold"&&!x.sold_at)return false;if(!q)return true;return [x.item_name,x.ign,x.contact,x.notes,x.category].map(v=>clean(v).toLowerCase()).join(" ").includes(q);});}
  function renderListings(){const grid=$("listing-grid");grid.replaceChildren();for(const row of filteredListings()){const state=row.is_hidden?"hidden":row.sold_at?"sold":"open",card=el("article","listing-card"),main=el("div","");const badges=el("div","badges");badges.append(el("span","badge",row.side),el("span","badge",row.category.replaceAll("_"," ")),el("span","badge "+state,state));main.append(badges,el("h3","",row.item_name));main.append(el("div","listing-line",`${fmtMesos(row.price_mesos)} • Qty ${row.quantity} • IGN ${row.ign}${row.negotiable?" • Negotiable":""}`));if(row.contact)main.append(el("div","listing-line",`Contact: ${row.contact}`));if(row.notes)main.append(el("div","listing-line",`Notes: ${row.notes}`));main.append(el("div","item-meta",`Created ${fmtDate(row.created_at)} • ID ${row.id}`));if(row.moderation_reason)main.append(el("div","item-meta",`Moderation: ${row.moderation_reason}`));const actions=el("div","listing-actions");const edit=el("button","","Edit");edit.onclick=()=>openListingEdit(row);actions.append(edit);const hide=el("button","",row.is_hidden?"Unhide":"Hide");hide.onclick=()=>row.is_hidden?unhideListing(row):hideListing(row);actions.append(hide);const sold=el("button","",row.sold_at?"Reopen":"Mark Sold");sold.onclick=()=>markSold(row,!row.sold_at);actions.append(sold);const del=el("button","danger","Delete");del.onclick=()=>deleteListing(row);actions.append(del);card.append(main,actions);grid.append(card);}}
  function openListingEdit(row){$("listing-id").value=row.id;$("listing-catalog-id").value=row.catalog_item_id||"";$("listing-side").value=row.side;$("listing-category").value=row.category;$("listing-item-name").value=row.item_name;$("listing-quantity").value=row.quantity;$("listing-price").value=row.price_mesos;$("listing-negotiable").checked=!!row.negotiable;$("listing-ign").value=row.ign;$("listing-contact").value=row.contact||"";$("listing-notes").value=row.notes||"";$("listing-form-status").textContent="";listingDialog.showModal();}
  async function saveListing(ev){ev.preventDefault();scopedStatus("listing-form-status","Saving…");const args={p_listing_id:$("listing-id").value,p_side:$("listing-side").value,p_category:$("listing-category").value,p_item_name:clean($("listing-item-name").value,60),p_quantity:Number($("listing-quantity").value),p_price_mesos:Number($("listing-price").value),p_negotiable:$("listing-negotiable").checked,p_ign:clean($("listing-ign").value,20),p_contact:clean($("listing-contact").value,80)||null,p_notes:clean($("listing-notes").value,240)||null,p_catalog_item_id:$("listing-catalog-id").value||null};const {error}=await db.rpc("market_staff_edit_listing",args);if(error){scopedStatus("listing-form-status",error.message,"error");return;}listingDialog.close();await loadListings();}
  async function hideListing(row){const reason=prompt("Moderation reason (max 120 characters):","Hidden by staff");if(reason===null)return;const {error}=await db.rpc("market_staff_hide_listing",{p_listing_id:row.id,p_reason:clean(reason,120)});if(error)return scopedStatus("listing-status",error.message,"error");await loadListings();}
  async function unhideListing(row){const {error}=await db.rpc("market_staff_unhide_listing",{p_listing_id:row.id});if(error)return scopedStatus("listing-status",error.message,"error");await loadListings();}
  async function markSold(row,sold){const {error}=await db.rpc("market_staff_mark_sold",{p_listing_id:row.id,p_sold:!!sold});if(error)return scopedStatus("listing-status",error.message,"error");await loadListings();}
  async function deleteListing(row){if(!confirm(`Permanently delete this post?\n\n${row.item_name}\nIGN: ${row.ign}\n\nThis also removes reports linked to it.`))return;const {error}=await db.rpc("market_staff_delete_listing",{p_listing_id:row.id});if(error)return scopedStatus("listing-status",error.message,"error");await loadListings();}

  async function loadReports(){scopedStatus("report-status","Loading reports…");if(!listings.length)await loadListings();const {data,error}=await db.from("market_reports").select("*").order("created_at",{ascending:false}).limit(500);if(error){console.error(error);scopedStatus("report-status",error.message,"error");return;}reports=Array.isArray(data)?data:[];scopedStatus("report-status",`Loaded ${reports.length} reports.`,"success");renderReports();}
  function renderReports(){const grid=$("report-grid");grid.replaceChildren();if(!reports.length){grid.append(el("article","report-card","No reports."));return;}const listingMap=new Map(listings.map(x=>[x.id,x]));for(const r of reports){const l=listingMap.get(r.listing_id),card=el("article","report-card");card.append(el("div","badges",undefined));card.lastChild.append(el("span","badge hidden",r.reason.replaceAll("_"," ")));card.append(el("h3","",l?.item_name||"Listing unavailable"));card.append(el("p","",r.details||"No extra details."));card.append(el("div","report-meta",`Listing ${r.listing_id} • Reporter ${r.reporter_id} • ${fmtDate(r.created_at)}`));if(l)card.append(el("div","report-meta",`IGN ${l.ign} • ${l.is_hidden?"Hidden":l.sold_at?"Sold":"Open"}`));grid.append(card);}}

  async function loadStaff(){if(role!=="editor")return;scopedStatus("team-status","Loading staff…");const {data,error}=await db.rpc("market_list_staff");if(error){scopedStatus("team-status",error.message,"error");return;}staff=Array.isArray(data)?data:[];scopedStatus("team-status",`Loaded ${staff.length} staff accounts.`,"success");renderStaff();}
  function renderStaff(){
    const grid=$("staff-grid");grid.replaceChildren();
    for(const s of staff){
      const card=el("article","staff-card");
      const identity=el("div","staff-identity");
      const avatar=el("div","staff-avatar");
      const display=clean(s.display_name,80)||"Discord user";
      if(s.avatar_url){const img=document.createElement("img");img.src=s.avatar_url;img.alt="";img.loading="lazy";img.referrerPolicy="no-referrer";img.onerror=()=>{avatar.replaceChildren();avatar.textContent=display.slice(0,1).toUpperCase();};avatar.append(img);}else avatar.textContent=display.slice(0,1).toUpperCase();
      const main=el("div","staff-main");
      main.append(el("div","staff-name",display),el("div","staff-role",roleLabel(s.role)),el("code","",s.user_id),el("div","item-meta",`Added ${fmtDate(s.created_at)}`));
      identity.append(avatar,main);
      const actions=el("div","staff-actions");
      if(s.user_id!==user.id){const del=el("button","danger","Remove Access");del.onclick=()=>removeStaff(s);actions.append(del);}else actions.append(el("span","badge verified","Current account"));
      card.append(identity,actions);grid.append(card);
    }
  }
  async function setStaff(ev){ev.preventDefault();const uid=clean($("staff-user-id").value,80),r=$("staff-role").value;if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(uid)){scopedStatus("team-status","Invalid UUID format.","error");return;}const {error}=await db.rpc("market_set_staff_role",{p_user_id:uid,p_role:r});if(error){scopedStatus("team-status",error.message,"error");return;}$("staff-form").reset();await loadStaff();}
  async function removeStaff(s){if(!confirm(`Remove ${roleLabel(s.role)} access for ${s.user_id}?`))return;const {error}=await db.rpc("market_remove_staff",{p_user_id:s.user_id});if(error){scopedStatus("team-status",error.message,"error");return;}await loadStaff();}

  async function downloadGuide(){scopedStatus("guide-status","Preparing private download…");const {data,error}=await db.storage.from("market-staff-private").download("KaiokenMS-Market-Staff-Guide.pdf");if(error){scopedStatus("guide-status",`Guide unavailable: ${error.message}. Upload the PDF to the private market-staff-private bucket first.`,"error");return;}const url=URL.createObjectURL(data),a=document.createElement("a");a.href=url;a.download="KaiokenMS-Market-Staff-Guide.pdf";a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);scopedStatus("guide-status","Guide downloaded.","success");}

  $("discord-login").onclick=async()=>{if(!db)return;const redirectTo=window.location.origin+window.location.pathname;const {error}=await db.auth.signInWithOAuth({provider:"discord",options:{redirectTo}});if(error)setAccess("bad","Discord login failed",error.message);};
  $("sign-out").onclick=async()=>{await db.auth.signOut();await refreshAuth();};
  $("add-item").onclick=openAddItem;$("item-name").addEventListener("input",()=>{if(!$("item-id").value)$("item-slug").value=slugify($("item-name").value);});itemForm.addEventListener("submit",saveItem);$("cancel-item").onclick=()=>itemDialog.close();$("search").addEventListener("input",renderItems);$("category-filter").addEventListener("change",renderItems);$("enabled-filter").addEventListener("change",renderItems);$("import-open").onclick=()=>{importForm.reset();$("import-status").textContent="";$("import-summary").textContent="Choose a CSV file. Rows are upserted by slug.";importDialog.showModal();};$("cancel-import").onclick=()=>importDialog.close();importForm.addEventListener("submit",importCSV);$("export-csv").onclick=exportCSV;$("csv-file").addEventListener("change",async()=>{const f=$("csv-file").files?.[0];if(!f)return;try{$("import-summary").textContent=`${f.name} • ${parseCSV(await f.text()).length} data rows detected`;}catch{$("import-summary").textContent="Could not preview CSV.";}});
  $("refresh-listings").onclick=loadListings;$("listing-search").addEventListener("input",renderListings);$("listing-state-filter").addEventListener("change",renderListings);$("listing-side-filter").addEventListener("change",renderListings);listingForm.addEventListener("submit",saveListing);$("cancel-listing").onclick=()=>listingDialog.close();$("refresh-reports").onclick=loadReports;$("refresh-team").onclick=loadStaff;$("staff-form").addEventListener("submit",setStaff);$("download-guide").onclick=downloadGuide;

  async function init(){if(!configured||!window.supabase){setAccess("bad","Configuration missing","market-config.js must contain the Supabase Project URL and publishable key.");return;}db=window.supabase.createClient(CONFIG.supabaseUrl,CONFIG.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});db.auth.onAuthStateChange(()=>setTimeout(refreshAuth,0));await refreshAuth();}
  init();
})();
